### ISSUE TITLE
Inference mode

### ISSUE THREAD

**Issue by guigxx** [akanimax/natural-language-summary-generation-from-structured-data#6]
Hi ! First great work thank you !
I don't get why we need label values for the inference mode. Is there a way to write a predict function directly from the input variables ? thx

**Comment by akanimax** [comment]
Hello @guigxx ! Thank you for the nod. It took me some time to go back into the code base. You are right. There is no need for the label values in the inference mode. In inference mode, all the ops are replicated with the reuse of weights from training. take a look here -> [Inference scope of computations](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/blob/master/TensorFlow_implementation/Summary_Generator/Tensorflow_Graph/order_planner_with_copynet.py#L517). 
As coded there, you only have to evaluate the `inf_outputs` tensor which upon retracing backwards does not have a dependency on the `labels` placeholder. Infact the `interface_dict` also returns the handle to the same under the key: `inference` [here](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/blob/master/TensorFlow_implementation/Summary_Generator/Tensorflow_Graph/order_planner_with_copynet.py#L561). 

To stay consistent with the structure of the code, you can add another method called infer in the class Model [here](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/blob/master/TensorFlow_implementation/Summary_Generator/Model.py) and then use the model API for inference.

The reason why I never ended up writing the infer method is because as soon as the model was trained, we directly started working on the TFServing part of it. Feel free to open a PR for the same.

**Comment by akanimax** [comment]
@guigxx Closing this issue now. LMK if you need any more help.
